version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ../.env

  web:
    image: vandruhav/foodgram-backend:v1
    restart: always
    volumes:
      - static_value:/foodgram/static_backend/
      - media_value:/foodgram/media_backend/
    env_file:
      - ../.env
    depends_on:
      - db

  frontend:
    image: vandruhav/foodgram_frontend:v1
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - web

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static_backend/
      - media_value:/var/html/media_backend/
    depends_on:
      - frontend

volumes:
  db_value:
  static_value:
  media_value:
