# Generated by Django 2.2.28 on 2022-11-10 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20221110_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes_of_ingredient', to='recipes.Ingredient', verbose_name='Ингредиент'),
        ),
    ]
